apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcds.druid.gardener.cloud
spec:
  additionalPrinterColumns:
    - JSONPath: .status.ready
      name: Ready
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: druid.gardener.cloud
  names:
    kind: Etcd
    listKind: EtcdList
    plural: etcds
    singular: etcd
  scope: Namespaced
  subresources:
    scale:
      labelSelectorPath: .status.labelSelector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
