apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-extension-validator-alicloud
webhooks:
- name: validation.alicloud.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  clientConfig:
    url: "https://localhost:9443/webhooks/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxRENDQWJ3Q0NRRFRRZUljMVpoRFZ6QU5CZ2txaGtpRzl3MEJBUVVGQURBc01SY3dGUVlEVlFRRERBNW4KWVhKa1pXNWxjaTVqYkc5MVpERVJNQThHQTFVRUNnd0laMkZ5WkdWdVpYSXdIaGNOTWpBd016RTVNRGd4TlRFegpXaGNOTWpFd016RTVNRGd4TlRFeldqQXNNUmN3RlFZRFZRUUREQTVuWVhKa1pXNWxjaTVqYkc5MVpERVJNQThHCkExVUVDZ3dJWjJGeVpHVnVaWEl3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2cKSmhITnhiZXZRdEhqbEtyMGZpaE8wb3BjRFFDMDRpdFk1S1pENGF1eDdQK0cvKy9XeDNaSEEvTjM2RytyRGFyYgpBMjFDZi9JUXFjNEx4MU1US21ORS9JNGJHTDhXTmM4b3QwWjBnU3czVTkrWWdhVlMwOFpaYmVaUnhwZ2dacjU5ClFQQ0ozTmdIeXd6NUlzR2Zwdk5ab1JRY0VXY2RrbWxqcTcySWo2VlFQSjR2V0NieFpqN1F4OVVZcWxUQUhpV0kKTmEzUFFJZnAvb1JGYm5Dem4veC95STVxM245NWd0NzVaQ3JhRWozMjJMSnR4NmorNUY3cVZSc1V1SE44bjdVZgpaMXhrd21aaE4zR0svbjNhWXVKaUpCaExDd0dzU3ZSSi9IL3I4ZEp4Wm5maW1lSldSSlFqbzBNa214VmhSRTRoCjdod1FyeXZtdGx2R3BQS2s5ZmFwQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVGQlFBRGdnRUJBQ3hqQVRLa3VKd0oKTUpiYUZpZGtoOUtUU2p6UHRKY2FEd092elZ0QWRVQ1R1SU5iVHdyaVh6RWczcUdXK21zMTdsRUp0MXY0UUxSago0aEdVSTlhU1lKelVMRllzbEg5bU5IbHhGc0E2aTJsWTBJWFFSTGNYdG9lZzIwbVEvY1Y0ZFpxc0wrOVplNGQxCnNUMjdXanNWRDBES2docDZBNmlRSWpMdDh5K2V1TzRhRXVEMnJkVkwzNDhYL1VRaVJNTVoraDlieXMwWjQ5NjkKa2VNN1pxMnB3Q0ZIWkhrM1pEemVWZzJyTEhwajMrSlIyREdoWUxkL0x0TEpJd2ZaaVp0eWlCb2JtL1JNbXRpWgpKT29PU1VxZnRQNTlaZWxXbWsxMUF3R1psakkvSmVQcitvcURWWmgrM3E1VWhUYkJaenpkRTJ1bTUrZ2plaHRNCjZCaGhZQThDMzR3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==