{{- if eq .Values.gardener.seed.provider "tencentcloud" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if eq .Values.gardener.seed.volumeProvider "FlexVolume" }}
provisioner: com.tencent.cloud.csi.cbs
parameters:
  type: CLOUD_SSD
  encrypted: "true"
{{- else }}
provisioner: com.tencent.cloud.csi.cbs
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: CLOUD_SSD
  readOnly: "false"
  encrypted: "true"
{{- end }}
{{- end }}
