images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "v1.4.0"
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.34.0"
- name: tencentcloud-controller-manager
  sourceRepository: https://github.com/TencentCloud/tencentcloud-cloud-controller-manager
  repository: ccr.ccs.tencentyun.com/library/tencentcloud-cloud-controller-manager
  tag: "1.0.1"
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: v1.0.1
  targetVersion: 1.13.x
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: v2.2.0
  targetVersion: ">= 1.14"
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v1.0.1
  targetVersion: 1.13.x
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v1.3.0
  targetVersion: ">= 1.14"
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: v1.0.2
  targetVersion: 1.13.x
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: v1.6.0
  targetVersion: ">= 1.14"
- name: csi-snapshotter
  sourceRepository: https://github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/csi-snapshotter
  tag: v1.0.2
  targetVersion: 1.13.x
- name: csi-snapshotter
  sourceRepository: https://github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/csi-snapshotter
  tag: v1.2.2
  targetVersion: ">= 1.14"
- name: csi-snapshotter
  sourceRepository: https://github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/csi-snapshotter
  tag: v2.1.1
  targetVersion: ">= 1.17"
- name: csi-snapshot-controller
  sourceRepository: https://github.com/kubernetes-csi/external-snapshotter
  repository: quay.io/k8scsi/snapshot-controller
  tag: v2.1.1
- name: csi-resizer
  sourceRepository: https://github.com/kubernetes-csi/external-resizer
  repository: quay.io/k8scsi/csi-resizer
  tag: v0.3.0
  targetVersion: 1.13.x
- name: csi-resizer
  sourceRepository: https://github.com/kubernetes-csi/external-resizer
  repository: quay.io/k8scsi/csi-resizer
  tag: v0.5.0
  targetVersion: ">= 1.14"
- name: csi-plugin-tencentcloud
  sourceRepository: https://github.com/TencentCloud/kubernetes-csi-tencentcloud
  repository: ccr.ccs.tencentyun.com/k8scsi/csi-tencentcloud-cbs
  tag: v1.2.0 # the upstream image is using non-semver tags which is causing issues in the CI/CD pipelines of Gardener, thus the image is replicated and tagged with semver version in another registry (registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin:v1.14.8.41-e97402d1-aliyun).
  targetVersion: ">= 1.14"
