global:
  virtualGarden:
    enabled: false
  image:
    repository: vesoft/validator-tencentcloud
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  webhookConfig:
    caBundle: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    serverPort: 10250
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
  # Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
  kubeconfig: