---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    resources.gardener.cloud/delete-on-invalid-update: "true"
provisioner: com.tencent.cloud.csi.cbs
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: CLOUD_SSD
  readOnly: "false"
  encrypted: "true"
