// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	tencentcloud "github.com/gardener/gardener-extension-provider-tencentcloud/pkg/apis/tencentcloud"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*tencentcloud.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_tencentcloud_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*tencentcloud.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*tencentcloud.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*tencentcloud.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_tencentcloud_CloudProfileConfig(a.(*CloudProfileConfig), b.(*tencentcloud.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*tencentcloud.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*tencentcloud.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_tencentcloud_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*tencentcloud.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*tencentcloud.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*tencentcloud.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_tencentcloud_InfrastructureConfig(a.(*InfrastructureConfig), b.(*tencentcloud.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*tencentcloud.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*tencentcloud.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_tencentcloud_InfrastructureStatus(a.(*InfrastructureStatus), b.(*tencentcloud.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*tencentcloud.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*tencentcloud.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_tencentcloud_MachineImage(a.(*MachineImage), b.(*tencentcloud.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_MachineImage_To_v1alpha1_MachineImage(a.(*tencentcloud.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*tencentcloud.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_tencentcloud_MachineImageVersion(a.(*MachineImageVersion), b.(*tencentcloud.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*tencentcloud.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*tencentcloud.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_tencentcloud_MachineImages(a.(*MachineImages), b.(*tencentcloud.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_MachineImages_To_v1alpha1_MachineImages(a.(*tencentcloud.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NatGatewayConfig)(nil), (*tencentcloud.NatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NatGatewayConfig_To_tencentcloud_NatGatewayConfig(a.(*NatGatewayConfig), b.(*tencentcloud.NatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.NatGatewayConfig)(nil), (*NatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(a.(*tencentcloud.NatGatewayConfig), b.(*NatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Networks)(nil), (*tencentcloud.Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Networks_To_tencentcloud_Networks(a.(*Networks), b.(*tencentcloud.Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.Networks)(nil), (*Networks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_Networks_To_v1alpha1_Networks(a.(*tencentcloud.Networks), b.(*Networks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionIDMapping)(nil), (*tencentcloud.RegionIDMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegionIDMapping_To_tencentcloud_RegionIDMapping(a.(*RegionIDMapping), b.(*tencentcloud.RegionIDMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.RegionIDMapping)(nil), (*RegionIDMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_RegionIDMapping_To_v1alpha1_RegionIDMapping(a.(*tencentcloud.RegionIDMapping), b.(*RegionIDMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroup)(nil), (*tencentcloud.SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroup_To_tencentcloud_SecurityGroup(a.(*SecurityGroup), b.(*tencentcloud.SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.SecurityGroup)(nil), (*SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_SecurityGroup_To_v1alpha1_SecurityGroup(a.(*tencentcloud.SecurityGroup), b.(*SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPC)(nil), (*tencentcloud.VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPC_To_tencentcloud_VPC(a.(*VPC), b.(*tencentcloud.VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.VPC)(nil), (*VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_VPC_To_v1alpha1_VPC(a.(*tencentcloud.VPC), b.(*VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCStatus)(nil), (*tencentcloud.VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VPCStatus_To_tencentcloud_VPCStatus(a.(*VPCStatus), b.(*tencentcloud.VPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.VPCStatus)(nil), (*VPCStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_VPCStatus_To_v1alpha1_VPCStatus(a.(*tencentcloud.VPCStatus), b.(*VPCStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VSwitch)(nil), (*tencentcloud.VSwitch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VSwitch_To_tencentcloud_VSwitch(a.(*VSwitch), b.(*tencentcloud.VSwitch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.VSwitch)(nil), (*VSwitch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_VSwitch_To_v1alpha1_VSwitch(a.(*tencentcloud.VSwitch), b.(*VSwitch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*tencentcloud.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_tencentcloud_WorkerStatus(a.(*WorkerStatus), b.(*tencentcloud.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*tencentcloud.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Zone)(nil), (*tencentcloud.Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Zone_To_tencentcloud_Zone(a.(*Zone), b.(*tencentcloud.Zone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tencentcloud.Zone)(nil), (*Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tencentcloud_Zone_To_v1alpha1_Zone(a.(*tencentcloud.Zone), b.(*Zone), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_tencentcloud_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *tencentcloud.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_tencentcloud_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_tencentcloud_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *tencentcloud.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_tencentcloud_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_tencentcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *tencentcloud.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_tencentcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_tencentcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *tencentcloud.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_tencentcloud_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_tencentcloud_CloudProfileConfig(in *CloudProfileConfig, out *tencentcloud.CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]tencentcloud.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_tencentcloud_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_tencentcloud_CloudProfileConfig(in *CloudProfileConfig, out *tencentcloud.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_tencentcloud_CloudProfileConfig(in, out, s)
}

func autoConvert_tencentcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *tencentcloud.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_tencentcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_tencentcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *tencentcloud.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_tencentcloud_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_tencentcloud_ControlPlaneConfig(in *ControlPlaneConfig, out *tencentcloud.ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*tencentcloud.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_tencentcloud_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_tencentcloud_ControlPlaneConfig(in *ControlPlaneConfig, out *tencentcloud.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_tencentcloud_ControlPlaneConfig(in, out, s)
}

func autoConvert_tencentcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *tencentcloud.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_tencentcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_tencentcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *tencentcloud.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_tencentcloud_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_tencentcloud_InfrastructureConfig(in *InfrastructureConfig, out *tencentcloud.InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_Networks_To_tencentcloud_Networks(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_tencentcloud_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_tencentcloud_InfrastructureConfig(in *InfrastructureConfig, out *tencentcloud.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_tencentcloud_InfrastructureConfig(in, out, s)
}

func autoConvert_tencentcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *tencentcloud.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_tencentcloud_Networks_To_v1alpha1_Networks(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_tencentcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_tencentcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *tencentcloud.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_tencentcloud_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_tencentcloud_InfrastructureStatus(in *InfrastructureStatus, out *tencentcloud.InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPCStatus_To_tencentcloud_VPCStatus(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.KeyPairName = in.KeyPairName
	out.MachineImages = *(*[]tencentcloud.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_tencentcloud_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_tencentcloud_InfrastructureStatus(in *InfrastructureStatus, out *tencentcloud.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_tencentcloud_InfrastructureStatus(in, out, s)
}

func autoConvert_tencentcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *tencentcloud.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_tencentcloud_VPCStatus_To_v1alpha1_VPCStatus(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.KeyPairName = in.KeyPairName
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_tencentcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_tencentcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *tencentcloud.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_tencentcloud_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_tencentcloud_MachineImage(in *MachineImage, out *tencentcloud.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.ID = in.ID
	return nil
}

// Convert_v1alpha1_MachineImage_To_tencentcloud_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_tencentcloud_MachineImage(in *MachineImage, out *tencentcloud.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_tencentcloud_MachineImage(in, out, s)
}

func autoConvert_tencentcloud_MachineImage_To_v1alpha1_MachineImage(in *tencentcloud.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.ID = in.ID
	return nil
}

// Convert_tencentcloud_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_tencentcloud_MachineImage_To_v1alpha1_MachineImage(in *tencentcloud.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_tencentcloud_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_tencentcloud_MachineImageVersion(in *MachineImageVersion, out *tencentcloud.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Regions = *(*[]tencentcloud.RegionIDMapping)(unsafe.Pointer(&in.Regions))
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_tencentcloud_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_tencentcloud_MachineImageVersion(in *MachineImageVersion, out *tencentcloud.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_tencentcloud_MachineImageVersion(in, out, s)
}

func autoConvert_tencentcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *tencentcloud.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Regions = *(*[]RegionIDMapping)(unsafe.Pointer(&in.Regions))
	return nil
}

// Convert_tencentcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_tencentcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *tencentcloud.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_tencentcloud_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_tencentcloud_MachineImages(in *MachineImages, out *tencentcloud.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]tencentcloud.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_tencentcloud_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_tencentcloud_MachineImages(in *MachineImages, out *tencentcloud.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_tencentcloud_MachineImages(in, out, s)
}

func autoConvert_tencentcloud_MachineImages_To_v1alpha1_MachineImages(in *tencentcloud.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_tencentcloud_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_tencentcloud_MachineImages_To_v1alpha1_MachineImages(in *tencentcloud.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_tencentcloud_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_NatGatewayConfig_To_tencentcloud_NatGatewayConfig(in *NatGatewayConfig, out *tencentcloud.NatGatewayConfig, s conversion.Scope) error {
	out.EIPAllocationID = (*string)(unsafe.Pointer(in.EIPAllocationID))
	return nil
}

// Convert_v1alpha1_NatGatewayConfig_To_tencentcloud_NatGatewayConfig is an autogenerated conversion function.
func Convert_v1alpha1_NatGatewayConfig_To_tencentcloud_NatGatewayConfig(in *NatGatewayConfig, out *tencentcloud.NatGatewayConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NatGatewayConfig_To_tencentcloud_NatGatewayConfig(in, out, s)
}

func autoConvert_tencentcloud_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(in *tencentcloud.NatGatewayConfig, out *NatGatewayConfig, s conversion.Scope) error {
	out.EIPAllocationID = (*string)(unsafe.Pointer(in.EIPAllocationID))
	return nil
}

// Convert_tencentcloud_NatGatewayConfig_To_v1alpha1_NatGatewayConfig is an autogenerated conversion function.
func Convert_tencentcloud_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(in *tencentcloud.NatGatewayConfig, out *NatGatewayConfig, s conversion.Scope) error {
	return autoConvert_tencentcloud_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(in, out, s)
}

func autoConvert_v1alpha1_Networks_To_tencentcloud_Networks(in *Networks, out *tencentcloud.Networks, s conversion.Scope) error {
	if err := Convert_v1alpha1_VPC_To_tencentcloud_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Zones = *(*[]tencentcloud.Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_v1alpha1_Networks_To_tencentcloud_Networks is an autogenerated conversion function.
func Convert_v1alpha1_Networks_To_tencentcloud_Networks(in *Networks, out *tencentcloud.Networks, s conversion.Scope) error {
	return autoConvert_v1alpha1_Networks_To_tencentcloud_Networks(in, out, s)
}

func autoConvert_tencentcloud_Networks_To_v1alpha1_Networks(in *tencentcloud.Networks, out *Networks, s conversion.Scope) error {
	if err := Convert_tencentcloud_VPC_To_v1alpha1_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Zones = *(*[]Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_tencentcloud_Networks_To_v1alpha1_Networks is an autogenerated conversion function.
func Convert_tencentcloud_Networks_To_v1alpha1_Networks(in *tencentcloud.Networks, out *Networks, s conversion.Scope) error {
	return autoConvert_tencentcloud_Networks_To_v1alpha1_Networks(in, out, s)
}

func autoConvert_v1alpha1_RegionIDMapping_To_tencentcloud_RegionIDMapping(in *RegionIDMapping, out *tencentcloud.RegionIDMapping, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	return nil
}

// Convert_v1alpha1_RegionIDMapping_To_tencentcloud_RegionIDMapping is an autogenerated conversion function.
func Convert_v1alpha1_RegionIDMapping_To_tencentcloud_RegionIDMapping(in *RegionIDMapping, out *tencentcloud.RegionIDMapping, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegionIDMapping_To_tencentcloud_RegionIDMapping(in, out, s)
}

func autoConvert_tencentcloud_RegionIDMapping_To_v1alpha1_RegionIDMapping(in *tencentcloud.RegionIDMapping, out *RegionIDMapping, s conversion.Scope) error {
	out.Name = in.Name
	out.ID = in.ID
	return nil
}

// Convert_tencentcloud_RegionIDMapping_To_v1alpha1_RegionIDMapping is an autogenerated conversion function.
func Convert_tencentcloud_RegionIDMapping_To_v1alpha1_RegionIDMapping(in *tencentcloud.RegionIDMapping, out *RegionIDMapping, s conversion.Scope) error {
	return autoConvert_tencentcloud_RegionIDMapping_To_v1alpha1_RegionIDMapping(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroup_To_tencentcloud_SecurityGroup(in *SecurityGroup, out *tencentcloud.SecurityGroup, s conversion.Scope) error {
	out.Purpose = tencentcloud.Purpose(in.Purpose)
	out.ID = in.ID
	return nil
}

// Convert_v1alpha1_SecurityGroup_To_tencentcloud_SecurityGroup is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroup_To_tencentcloud_SecurityGroup(in *SecurityGroup, out *tencentcloud.SecurityGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroup_To_tencentcloud_SecurityGroup(in, out, s)
}

func autoConvert_tencentcloud_SecurityGroup_To_v1alpha1_SecurityGroup(in *tencentcloud.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.ID = in.ID
	return nil
}

// Convert_tencentcloud_SecurityGroup_To_v1alpha1_SecurityGroup is an autogenerated conversion function.
func Convert_tencentcloud_SecurityGroup_To_v1alpha1_SecurityGroup(in *tencentcloud.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	return autoConvert_tencentcloud_SecurityGroup_To_v1alpha1_SecurityGroup(in, out, s)
}

func autoConvert_v1alpha1_VPC_To_tencentcloud_VPC(in *VPC, out *tencentcloud.VPC, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	return nil
}

// Convert_v1alpha1_VPC_To_tencentcloud_VPC is an autogenerated conversion function.
func Convert_v1alpha1_VPC_To_tencentcloud_VPC(in *VPC, out *tencentcloud.VPC, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPC_To_tencentcloud_VPC(in, out, s)
}

func autoConvert_tencentcloud_VPC_To_v1alpha1_VPC(in *tencentcloud.VPC, out *VPC, s conversion.Scope) error {
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	return nil
}

// Convert_tencentcloud_VPC_To_v1alpha1_VPC is an autogenerated conversion function.
func Convert_tencentcloud_VPC_To_v1alpha1_VPC(in *tencentcloud.VPC, out *VPC, s conversion.Scope) error {
	return autoConvert_tencentcloud_VPC_To_v1alpha1_VPC(in, out, s)
}

func autoConvert_v1alpha1_VPCStatus_To_tencentcloud_VPCStatus(in *VPCStatus, out *tencentcloud.VPCStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.VSwitches = *(*[]tencentcloud.VSwitch)(unsafe.Pointer(&in.VSwitches))
	out.SecurityGroups = *(*[]tencentcloud.SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	return nil
}

// Convert_v1alpha1_VPCStatus_To_tencentcloud_VPCStatus is an autogenerated conversion function.
func Convert_v1alpha1_VPCStatus_To_tencentcloud_VPCStatus(in *VPCStatus, out *tencentcloud.VPCStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VPCStatus_To_tencentcloud_VPCStatus(in, out, s)
}

func autoConvert_tencentcloud_VPCStatus_To_v1alpha1_VPCStatus(in *tencentcloud.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.VSwitches = *(*[]VSwitch)(unsafe.Pointer(&in.VSwitches))
	out.SecurityGroups = *(*[]SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	return nil
}

// Convert_tencentcloud_VPCStatus_To_v1alpha1_VPCStatus is an autogenerated conversion function.
func Convert_tencentcloud_VPCStatus_To_v1alpha1_VPCStatus(in *tencentcloud.VPCStatus, out *VPCStatus, s conversion.Scope) error {
	return autoConvert_tencentcloud_VPCStatus_To_v1alpha1_VPCStatus(in, out, s)
}

func autoConvert_v1alpha1_VSwitch_To_tencentcloud_VSwitch(in *VSwitch, out *tencentcloud.VSwitch, s conversion.Scope) error {
	out.Purpose = tencentcloud.Purpose(in.Purpose)
	out.ID = in.ID
	out.Zone = in.Zone
	return nil
}

// Convert_v1alpha1_VSwitch_To_tencentcloud_VSwitch is an autogenerated conversion function.
func Convert_v1alpha1_VSwitch_To_tencentcloud_VSwitch(in *VSwitch, out *tencentcloud.VSwitch, s conversion.Scope) error {
	return autoConvert_v1alpha1_VSwitch_To_tencentcloud_VSwitch(in, out, s)
}

func autoConvert_tencentcloud_VSwitch_To_v1alpha1_VSwitch(in *tencentcloud.VSwitch, out *VSwitch, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.ID = in.ID
	out.Zone = in.Zone
	return nil
}

// Convert_tencentcloud_VSwitch_To_v1alpha1_VSwitch is an autogenerated conversion function.
func Convert_tencentcloud_VSwitch_To_v1alpha1_VSwitch(in *tencentcloud.VSwitch, out *VSwitch, s conversion.Scope) error {
	return autoConvert_tencentcloud_VSwitch_To_v1alpha1_VSwitch(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_tencentcloud_WorkerStatus(in *WorkerStatus, out *tencentcloud.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]tencentcloud.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_tencentcloud_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_tencentcloud_WorkerStatus(in *WorkerStatus, out *tencentcloud.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_tencentcloud_WorkerStatus(in, out, s)
}

func autoConvert_tencentcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in *tencentcloud.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_tencentcloud_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_tencentcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in *tencentcloud.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_tencentcloud_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}

func autoConvert_v1alpha1_Zone_To_tencentcloud_Zone(in *Zone, out *tencentcloud.Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.Worker = in.Worker
	out.Workers = in.Workers
	out.NatGateway = (*tencentcloud.NatGatewayConfig)(unsafe.Pointer(in.NatGateway))
	return nil
}

// Convert_v1alpha1_Zone_To_tencentcloud_Zone is an autogenerated conversion function.
func Convert_v1alpha1_Zone_To_tencentcloud_Zone(in *Zone, out *tencentcloud.Zone, s conversion.Scope) error {
	return autoConvert_v1alpha1_Zone_To_tencentcloud_Zone(in, out, s)
}

func autoConvert_tencentcloud_Zone_To_v1alpha1_Zone(in *tencentcloud.Zone, out *Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.Worker = in.Worker
	out.Workers = in.Workers
	out.NatGateway = (*NatGatewayConfig)(unsafe.Pointer(in.NatGateway))
	return nil
}

// Convert_tencentcloud_Zone_To_v1alpha1_Zone is an autogenerated conversion function.
func Convert_tencentcloud_Zone_To_v1alpha1_Zone(in *tencentcloud.Zone, out *Zone, s conversion.Scope) error {
	return autoConvert_tencentcloud_Zone_To_v1alpha1_Zone(in, out, s)
}
