replicas: 1
clusterName: shoot-foo-bar
kubernetesVersion: 1.7.5
podNetwork: 192.168.0.0/16
podAnnotations: {}
podLabels: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images:
  alicloud-controller-manager: image-repository
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 300Mi
cloudConfig: json-values
