apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: controlplane
    app: kubernetes
    role: cloud-controller-manager
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: cloud-controller-manager
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        garden.sapcloud.io/role: controlplane
        app: kubernetes
        role: cloud-controller-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-alicloud-networks: allowed
        networking.gardener.cloud/from-prometheus: allowed
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: tencentcloud-cloud-controller-manager
        image: {{ index .Values.images "alicloud-controller-manager" }}
        imagePullPolicy: IfNotPresent
        command:
        - /bin/tencentcloud-cloud-controller-manager
        - --cloud-provider=tencentcloud
        - --allocate-node-cidrs=true
        - --cluster-cidr={{ .Values.podNetwork }}
        - --configure-cloud-routes=true
        - --allow-untagged-cloud=true
        - --node-monitor-period=60s
        - --route-reconciliation-period=60s
        {{- include "cloud-controller-manager.featureGates" . | trimSuffix "," | indent 8 }}
        env:
        - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION
          valueFrom:
            secretKeyRef:
              name: tencentcloud-cloud-controller-manager-config
              key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION
        - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: tencentcloud-cloud-controller-manager-config
              key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID
        - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tencentcloud-cloud-controller-manager-config
              key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY
        - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE
          valueFrom:
            secretKeyRef:
              name: tencentcloud-cloud-controller-manager-config
              key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE
        - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID
          valueFrom:
            secretKeyRef:
              name: tencentcloud-cloud-controller-manager-config
              key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID
        ports:
        - containerPort: 10253
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTP
            port: 10253
          successThreshold: 1
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        ports:
        - containerPort: 10253
          name: metrics
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: cloud-controller-manager
          mountPath: /var/lib/cloud-controller-manager
        - name: cloud-provider-config
          mountPath: /etc/kubernetes/cloudprovider
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloud-controller-manager
        secret:
          secretName: cloud-controller-manager
      - name: cloud-provider-config
        secret:
          secretName: cloud-provider-config
