{{- if .Values.config.machineImageOwnerSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.machineImageOwnerSecret.name }}
  namespace: {{ .Release.Namespace }}
data:
  accessKeyID: {{ .Values.config.machineImageOwnerSecret.accessKeyID }}
  accessKeySecret: {{ .Values.config.machineImageOwnerSecret.accessKeySecret }}
type: Opaque
{{- end }}
